# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenTrack – The complete competition management suite
email: info@opentrack.run
author: OpenTrack
description: >- # this means to ignore newlines until "baseurl:"
  The complete competition management suite for athletics organisers.
  Our open cloud platform saves time for organisers and volunteers
  and makes it more fun for participants, helping the sport to grow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opentrack.run" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
date_format: "%b %-d, %Y"
google_analytics: 'UA-XXXXXXXX-X'
# 
# header_pages: 
#   - product.md
#   - results.md 
#   - team.html
#   - register.md 
 
# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons
#  - jekyll-menus

# Webpack handling sass
#sass:
#  load_paths:
#    - _sass
#    - node_modules

# Make sure the `_site/assets/` is not trashed (webpack output)
# keep_files:
#  - dist

collections:
  - team

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .git/
  - .github/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - yarn.lock
  - "*.lock"
  - "*.log"
